.TH "dstrboundscheck" 3 "18 July 2007" "dstrboundscheck" "Dstring Library"

.SH NAME
dstrboundscheck - Checks an index to see if it's within the bounds of a \
dstring_t buffer

.SH SYNOPSIS
.B "#include <dstring.h>"
.br

.B "int dstrboundscheck(dstring_t str, size_t index);"
.br

.SH DESCRIPTION

.B "dstrboundscheck()"
checks to see if a given index is or isn't within bounds of a dstring_t buffer.

Possible dstrerrno values:

DSTR_SUCCESS if the index is within bounds
.br
DSTR_OUT_OF_BOUNDS if the index is out of bounds
.br
DSTR_UNINITIALIZED if the dstring_t object is uninitialized

.SH RETURN VALUE

This function returns the value of dstrerrno.

.SH SEE ALSO
None.
